### ISSUE TITLE
Add cache manifest file for offline usage

### ISSUE THREAD

**Issue by jthornsen** [johreh/gloomycompanion#13]
To allow users to save the page and view offline, need to add a manifest file with all the images.

See https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/Client-SideStorage/Client-SideStorage.html for example implementation.

**Comment by johreh** [comment]
Offline mode _should_ work now (it does on my Chrome/Android at least). Re-open issue if something's not as expected.

**Comment by jthornsen** [comment]
yep thanks, it's working fine for me now on all my devices.
