### ISSUE TITLE
+/- buttons on spinner clips

### ISSUE THREAD

**Issue by johreh** [johreh/gloomycompanion#30]
![screenshot_2017-03-29_22-18-35](https://cloud.githubusercontent.com/assets/1417219/24474841/3c92ec8c-14ce-11e7-9668-0a5ded4101b6.png)

**Comment by GinoGalotti** [comment]
I'm trying in my browser and I never get that (I see some clipping, but WAY less than half of the symbol). If you make the browser as small as possible, you can see it fully; so I assume is some kind of aspect ratio when getting bigger. Will try to look at it, although will be nice to know what you did to see it that way, so I can verify the fix!
