### ISSUE TITLE
Shuffle algorithm is biased

### ISSUE THREAD

**Issue by abies** [johreh/gloomycompanion#39]
Current implementation of shuffle algorithm does

    for (var i = 0; i < l.length; i++) {
        var switch_index = Math.floor(Math.random() * l.length);

This unfortunately results in biased shuffle. Please read https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Implementation_errors for details. Proper shuffle will be something like

    for (var i = 0; i < l.length-1; i++) {
        var switch_index = i + Math.floor(Math.random() * (l.length-i));

Please doublecheck proposed solution - I might be off by one here (wikipedia uses ranges instead of arithmetics).

**Comment by GinoGalotti** [comment]
Wow. I thought about this, using a "Real random" instead of Math.Random... but then I thought _I doubt people know how to shuffle a deck of 8 cards properly when they play_... Feel free to create a pull request doing the change! Otherwise, if you can't, I'll try to make it myself next week. But nice catch!

**Comment by abies** [comment]
I don't think that randomness of the random generator itself will be noticeable here - at least compared to above bias. For 8 cards, it would be probably giving something between 10-15% for specific position combinations instead of expected 12.5%.

But you are right that in many cases, human shuffle can be a lot worse - there is a nice story about people doing it wrong in bridge tournaments for ages https://www.youtube.com/watch?v=RIGJH12vVCY&feature=youtu.be&t=4m35s

**Comment by GinoGalotti** [comment]
http://thepenry.net/jsrandom.php For the record, this one seems to work. 
Math.random() * (max - min + 1) + min

**Comment by GinoGalotti** [comment]
This has been merged... feel free to do whatever stress test you want to verify it :p !
