### ISSUE TITLE
Curse and bless cards should have limit

### ISSUE THREAD

**Issue by sztrzask** [johreh/gloomycompanion#54]
Both curse and bless should have hard coded limit. There's only 10 monster deck specific curses and (I think, not sure) the same amount of blesses.

**Comment by AndClarke** [comment]
This is done in a PR, though I don't know who pushes these things or when.

**Comment by nickv2002** [comment]
If @johreh doesn't accept this commit you can try pushing to this fork that has been updating instead:

https://github.com/g1ul10/gloomycompanion

**Comment by GinoGalotti** [comment]
This should be fixed now, please check it when you can. Thanks for using the app, feel free to reopen if it's still missing anything!
