### ISSUE TITLE
Missing range on Flame Demon card

### ISSUE THREAD

**Issue by ckevin** [johreh/gloomycompanion#56]
I think this Flame Demon card is missing a range value:
` [true,  "30", "* <table align='center'><tr> <td>  %fire%%use_element%: </td> <td> <span class='small'>All adjacent enemies<br/>suffer 2 damage.</span> </td> </tr> </table>", "* %move% +0", "* %attack% -2", "** %wound%","** %target% 2"]`
There is no gray hex on the card, so it should use the Flame Demon's default range, shouldn't it?

**Comment by ckevin** [comment]
To clarify, I think the "all adjacent enemies" text applies only to the first Consume Fire ability on the card (which is not actually an attack, and does not draw a modifier card.)  I think it is irrelevant to the subsequent Attack ability, which has no melee signifiers ("adjacent enemies" or a gray hex), so the Attack should use the enemy's default range.

**Comment by g1ul10** [comment]
That's correct. I added the required modification to my open pull request.

**Comment by GinoGalotti** [comment]
This should be fixed now, please check it when you can. Thanks for using the app, feel free to reopen if it's still missing anything!
