### ISSUE TITLE
Chrome on Android - can not scroll down to apply button.

### ISSUE THREAD

**Issue by nmeissner-scottlogic** [johreh/gloomycompanion#6]
If I use the app on Android (Chrome browser) I can't scroll down far enough to reach then "Apply" button and therefore can't add card decks.

Maybe adding a bit of margin add the bottom? Or put the button at the top?

(Love the app)

Cheers,
Nils

**Comment by GinoGalotti** [comment]
Nice catch, happens in both tabs (Scenario and Monsters).

**Comment by johreh** [comment]
*sigh*

It works in chrome on other devices and it works in other browsers on the phone. No idea why chrome on Android behaves differently. Will look into it. 

I may move the button, but I'm a bit worried the last scenarios will just be obscured instead.
