### ISSUE TITLE
Feature: If reshuffle has been drawn, shuffle icon should change color

### ISSUE THREAD

**Issue by Davst** [johreh/gloomycompanion#63]
If a reshuffle (/) or (2x) card is drawn, the reshuffle icon should change color to signify this and remind to reshuffle.

**Comment by Krizzzn** [comment]
I've implemented this in pull request #58, which waits for merge. You can try this feature here: https://krizzzn.github.io/gloomycompanion/

**Comment by Davst** [comment]
Good to hear. I looked at it, works nice. Kinda in the mood to contribute a bit myself, more design and gui wise.. Just need to figure out where/what i should base upon.

**Comment by GinoGalotti** [comment]
It has landed Master, please check if this is what you need! :) Thanks for using the app!

**Comment by goldaryn** [comment]
I see this feature on Krizzzn's version, which I am using, but not on main.

**Comment by Krizzzn** [comment]
Check my latest comment on #61. There I describe the problem.

**Comment by goldaryn** [comment]
Refreshing the browser cache did the trick. Thanks!

**Comment by goldaryn** [comment]
Thanks to your work, I can now change the color.

If anyone wants to do this in CSS without hosting a new icon image, it's possible as follows:

div.counter-icon.shuffle:not([class*=not-required]) {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjQwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4gPG1ldGFkYXRhIGlkPSJtZXRhZGF0YTM3NzYiPmltYWdlL3N2Zyt4bWw8L21ldGFkYXRhPiA8ZGVmcz4gIDxjbGlwUGF0aCBpZD0iY2xpcFBhdGgzNzg2IiBjbGlwUGF0aFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+ICAgPHBhdGggaWQ9InBhdGgzNzg0IiBkPSJtMCwzMDBsMzAwLDBsMCwtMzAwbC0zMDAsMGwwLDMwMHoiLz4gIDwvY2xpcFBhdGg+IDwvZGVmcz4gPGc+ICA8dGl0bGU+YmFja2dyb3VuZDwvdGl0bGU+ICA8cmVjdCBmaWxsPSJub25lIiBpZD0iY2FudmFzX2JhY2tncm91bmQiIGhlaWdodD0iNDAyIiB3aWR0aD0iNTgyIiB5PSItMSIgeD0iLTEiLz4gPC9nPiA8Zz4gIDx0aXRsZT5MYXllciAxPC90aXRsZT4gIDxnIHRyYW5zZm9ybT0ibWF0cml4KDEuMzMzMzMzMywwLDAsLTEuMzMzMzMzMywwLDQwMCkgIiBpZD0iZzM3NzgiPiAgIDxnIGlkPSJnMzc4MCI+ICAgIDxnIGNsaXAtcGF0aD0idXJsKCNjbGlwUGF0aDM3ODYpIiBpZD0iZzM3ODIiPiAgICAgPGcgaWQ9ImczNzg4Ij4gICAgICA8cGF0aCBmaWxsPSIjZmYwMDAwIiBmaWxsLXJ1bGU9Im5vbnplcm8iIGlkPSJwYXRoMzc5MCIgZD0ibTI2OS45MjU4MTIsMTU2LjEzMjAwNGMtMS41MzcsMjkuNjMyIC0xMy44MDQsNTcuMjczIC0zNC45NCw3OC40MTFjLTIyLjY0MiwyMi42NDEgLTUyLjc0OCwzNS4xMTMgLTg0Ljc2NywzNS4xMTNjLTMyLjAxOSwwIC02Mi4xMjEsLTEyLjQ3MiAtODQuNzYyLC0zNS4xMTNjLTEyLjU1MiwtMTIuNTUzIC0yMS45NywtMjcuMzk5IC0yNy44NzYsLTQzLjU5M2wzNC43ODYsMzUuNDY2bDkuNjQyLC0zNC42MjJjMTQuMTMxLDIyLjg1OSAzOS40MTksMzguMTI0IDY4LjIxLDM4LjEyNGMzOC4zNTMsMCA3MC40OTMsLTI3LjA4MyA3OC4zMTQsLTYzLjEyOGwtMTYuNzA4LDQuMzAybDIxLjI2NSwtNzYuMzQzbDU1LjQ5MSw1Ni41NzlsLTE4LjY1NSw0LjgwNHoiLz4gICAgIDwvZz4gICAgIDxnIGlkPSJnMzc5MiI+ICAgICAgPHBhdGggZmlsbD0iI2ZmMDAwMCIgZmlsbC1ydWxlPSJub256ZXJvIiBpZD0icGF0aDM3OTQiIGQ9Im0yMjcuNjM4NzAyLDczLjU4OTEwNGwtOS42NDIsMzQuNjIxYy0xNC4xMjcsLTIyLjg2NCAtMzkuNDIsLTM4LjEyOSAtNjguMjE1LC0zOC4xMjljLTM4LjM1MywwIC03MC40OTMsMjcuMDgzIC03OC4zMTQsNjMuMTI4bDE2LjcwNiwtNC4zMDNsLTIxLjI2LDc2LjM0NWwtNTUuNDk0LC01Ni41NzZsMTguNjU1LC00LjgwNWMxLjUzNiwtMjkuNjM0IDEzLjgwMiwtNTcuMjc1IDM0Ljk0LC03OC40MTNjMjIuNjQxLC0yMi42NDUgNTIuNzQ4LC0zNS4xMTMgODQuNzY3LC0zNS4xMTNjMzIuMDE5LDAgNjIuMTIxLDEyLjQ2OCA4NC43NjEsMzUuMTEzYzEyLjU1NywxMi41NTggMjEuOTg2LDI3LjQwNCAyNy44ODYsNDMuNjAzbC0zNC43OSwtMzUuNDcxeiIvPiAgICAgPC9nPiAgICA8L2c+ICAgPC9nPiAgPC9nPiA8L2c+PC9zdmc+)!important;
}

**Comment by GinoGalotti** [comment]
But... does it make sense to change the colour? Right now, it is only active when it's possible to draw, so why is the change of colour needed?
