### ISSUE TITLE
Web version is down

### ISSUE THREAD

**Issue by mihomir** [johreh/gloomycompanion#69]
Currently when trying to open 
https://johreh.github.io/gloomycompanion/

Instead of the page loading, a 404 error is received.

**Comment by GinoGalotti** [comment]
You're completely right. I f**ed up the branch, and I don't have the rights to change the configuration of the repo. 

https://ginogalotti.github.io/gloomycompanion/ Has the latest version, I'll try to contact the owner of the repo.

**Comment by GinoGalotti** [comment]
Tagging @johreh, hopefully he can read it!

**Comment by johreh** [comment]
Dang, that was a tricky one. Fixed in 7df6bbc1a712bcd649ba24e53bb67a41d411857b.
