### ISSUE TITLE
single-click reveal

### ISSUE THREAD

**Issue by vdv7** [johreh/gloomycompanion#78]
there's no need for separately clicking each monster's card, they can all be revealed at the same time with a single click.

adding a single button [Next Round] could take care of lots of mouse-movements and mouse-clicks in one shot (including the shuffling clicks)

the whole point of gloomycompanion is to remove much of the fiddliness of goomhaven, so this would definitely serve to aid with that goal, especially when there are many monster types.

**Comment by GrandVizierOlaf** [comment]
I've added one in my fork and can create a PR if it is appealing.
https://grandvizierolaf.github.io/gloomycompanion/

**Comment by GinoGalotti** [comment]
We've already talked about this. The "reshuffle" button was initially a new round one, but we were missing the ability to 'disable' decks so it was breaking the gameplay. We don't have that limitation now, so it should be straightforward to implement. https://github.com/johreh/gloomycompanion/issues/64 talks about it (so I'll close this as duplicate ;) ). If you think you really need it, feel free to aim for a merge with your branch @GrandVizierOlaf
