### ISSUE TITLE
Scenario #92 has wrong enemies

### ISSUE THREAD

**Issue by HarlanCS4J** [johreh/gloomycompanion#88]
Scenerio #92 looks like:
        { name: "#92 Back Alley Brawl"
        , decks:
            [   {"name": "Bandit Guard"}
            ,   {"name": "City Guard"}
            ,   {"name": "Inox Guard"}
            ,   {"name": "Bandit Archer"}
            ,   {"name": "City Archer"}
            ,   {"name": "Savvas Icestorm"}
            ,   {"name": "Frost Demon"}
            ,   {"name": "Wind Demon"}
            ]
},

It should read:
        { name: "#92 Back Alley Brawl"
        , decks:
            [   {"name": "Bandit Guard"}
            ,   {"name": "City Guard"}
            ,   {"name": "Inox Guard"}
            ,   {"name": "Bandit Archer"}
            ,   {"name": "City Archer"}
            ,   {"name": "Savvas Lavaflow"}
            ,   {"name": "Flame Demon"}
            ,   {"name": "Earth Demon"}
            ]
},

**Comment by GinoGalotti** [comment]
Thanks for the heads up! :) I'll change it ASAP!

**Comment by GinoGalotti** [comment]
Should be done now! Feel free to take a look! (You might need to refresh your browser without cache; it's Command + R on Mac... can't remember how to do it on windows!)

**Comment by HarlanCS4J** [comment]
You swapped the Savvas, but it's still the wrong demons.

**Comment by GinoGalotti** [comment]
You are completely right! I just swapped that too. Note to self: Next time double check instead of just rushing it at work. :)
